aiohttp==3.8.1
aiosignal==1.2.0
analytics-python==1.4.0
anyio==3.6.1
asgiref==3.5.2
astor==0.8.1
astunparse==1.6.3
async-timeout==4.0.2
asynctest==0.13.0
attrs==21.4.0
Babel==2.10.1
backoff==1.10.0
bce-python-sdk==0.8.64
bcrypt==3.2.2
bleach==5.0.0
cached-property
certifi==2020.6.20
cffi
cfgv==3.3.1
chardet==3.0.4
charset-normalizer==2.0.12
click==8.1.3
colorama==0.4.4
colorlog==6.6.0
commonmark==0.9.1
ConfigArgParse==1.2.3
cryptography==37.0.2
cycler==0.10.0
datasets==2.2.2
decorator==4.4.2
dill==0.3.4
distlib==0.3.4
docutils==0.18.1
easydict==1.9
efficientnet-pytorch==0.6.3
fastapi==0.78.0
ffmpy==0.3.0
filelock==3.2
Flask==2.1.2
Flask-Babel==2.0.0
flatbuffers==23.3.3
frozenlist==1.3.0
fsspec==2022.5.0
future==0.18.2
gast==0.4.0
gdown==3.12.2
google-pasta==0.2.0
gradio==3.0.4
grpcio==1.29.0
grpcio-tools==1.29.0
gunicorn==20.1.0
h11==0.13.0
h5py
huggingface-hub==0.6.0
identify==2.5.1
idna==2.10
imageio==2.9.0
importlib-metadata==4.11.3
itsdangerous==2.1.2
jeepney==0.8.0
jieba==0.42.1
Jinja2==3.1.2
joblib==1.1.0
keras==2.11.0
keyring==23.5.0
kiwisolver==1.2.0
libclang==15.0.6.1
linkify-it-py==1.0.3
markdown-it-py==2.1.0
MarkupSafe==2.1.1
matplot==0.1.9
matplotlib==3.3.1
mccabe==0.6.1
mdit-py-plugins==0.3.0
mdurl==0.1.1
mkl-fft==1.2.0
mkl-random==1.2.0
mkl-service==2.3.0
monotonic==1.6
multidict==6.0.2
multiprocess==0.70.12.2
munch==2.5.0
networkx==2.5
nodeenv==1.6.0
numpy==1.19.5
olefile==0.46
onnx==1.9.0
opencv-contrib-python==3.4.2.17
opencv-python==3.4.2.17
opt-einsum==3.3.0
orjson==3.6.8
packaging==23.0
paddle-bfloat==0.1.2
paddle2onnx==0.9.6
paddlefsl==1.1.0
paddlehub==2.2.0
paddlenlp==2.3.1
paddlepaddle==2.3.0
pandas==1.3.5
paramiko==2.11.0
path==16.4.0
Pillow==8.1.1
pkginfo==1.8.2
platformdirs==2.5.2
pre-commit==2.19.0
pretrainedmodels==0.7.4
protobuf==3.19.6
ptflops==0.6.9
pyarrow==8.0.0
pycparser
pycryptodome==3.14.1
pydantic==1.9.1
pydegensac==0.1.2
pydub==0.25.1
Pygments==2.12.0
pyloco==0.0.139
PyNaCl==1.5.0
pyparsing==2.4.7
PySocks==1.7.1
python-dateutil==2.8.1
python-multipart==0.0.5
pytz==2022.1
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==23.0.0
rarfile==4.0
readme-renderer==35.0
requests==2.24.0
requests-toolbelt==0.9.1
responses==0.18.0
rfc3986==2.0.0
rich==12.4.1
SciencePlots==2.0.1
scikit-image==0.15.0
scikit-learn==1.0.2
scipy==1.3.1
SecretStorage==3.3.2
segmentation-models-pytorch 
sentencepiece==0.1.96
seqeval==1.2.2
shellcheck-py==0.8.0.4
SimpleWebSocketServer==0.1.1
six==1.16.0
sniffio==1.2.0
starlette==0.19.1
tabulate==0.8.9
tensorboardX==2.1
termcolor==2.2.0
threadpoolctl==3.1.0
timm==0.3.2
toml==0.10.2
torch==1.11.0
torchaudio
torchstat==0.0.7
torchvision==0.12.0
tqdm==4.62.1
twine
typing==3.7.4.3
typing-extensions==4.2.0
uc-micro-py==1.0.1
urllib3
ushlex==0.99.1
uvicorn==0.17.6
virtualenv==20.14.1
visualdl==2.2.3
webencodings==0.5.1
websocket-client==1.3.2
Werkzeug==2.1.2
wrapt==1.15.0
xxhash==3.0.0
yarl==1.7.2
zipp==3.8.0
